server:
  port: 8081
spring:
  application:
    name: ucms-platform
  datasource:
    url: jdbc:mariadb://localhost:3306/ucms_platform
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848